export const ACTION_TYPES = {
  GET: "GET",
  GET_SUCCESS: "GET_SUCCESS",
  GET_ERROR: "GET_ERROR",

  DELETE: "DELETE",
  DELETE_SUCCESS: "DELETE_SUCCESS",

  UPDATE: "UPDATE",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",

  CREATE: "CREATE",
  CREATE_SUCCESS: "CREATE_SUCCESS"
}